train:
  experiment_name: 'freqwise_71_modmlp'
  device: 'cuda:0'
  seed: false
  logging_level: DEBUG
  save_model: true
  output_folder: /mnt/evo/data/fourier_video/exps
generator:
  renderrer:
    arch: CoordMLP
    internal_dim: 128
    num_freqs: 260
    num_layers: 8
    act: LeakyReLU
    ff_func: GaussianFourierFeatureTransform
    conv: ConLinear
  modulator:
    arch: PhaseMLP
    internal_dim: 64
    num_freqs: 260
    num_layers: 4
    act: LeakyReLU
    ff_func: GaussianFourierFeatureTransform
    conv: ConLinear
  phase_mod: true
  phase_mod_type: freqwise
data:
  dset_folder: /mnt/evo/data/fourier_video/data/frames/71
  batch_size: 2
  resolution: [256, 256]
