experiment_name: 'time'
device: 'cuda:1'
phase_mod: false
phase_mod_type: None
internal_dim: 64
num_layers: 10
act: LeakyReLU
dset_folder: ./frames/71
batch_size: 4
resolution: [256, 256]
seed: false
logging_level: DEBUG
